include make/all_head.mk

# If you want to create more targets, feel free
# to write the makefiles and include them here.
include make/project.mk
include make/project-test.mk

include make/all_tail.mk
